# Generated by Django 2.1.7 on 2019-03-16 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oculto', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Matéria',
                'verbose_name_plural': 'Matérias',
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=256)),
                ('aprovado', models.BooleanField(default=False)),
                ('curso', models.CharField(default=None, max_length=256)),
                ('instituicao', models.CharField(default=None, max_length=256, verbose_name='Instituição')),
                ('estudantes', models.ManyToManyField(through='app.Contato', to='app.Estudante')),
                ('materia', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.Materia', verbose_name='Matéria')),
            ],
            options={
                'verbose_name_plural': 'Mentores',
            },
        ),
        migrations.AddField(
            model_name='contato',
            name='estudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Estudante'),
        ),
        migrations.AddField(
            model_name='contato',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Mentor'),
        ),
    ]
