# Generated by Django 2.1.7 on 2019-03-17 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190317_0118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contato',
            new_name='Solicitacao',
        ),
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'verbose_name': 'Solicitação', 'verbose_name_plural': 'Solicitações'},
        ),
    ]
