# Generated by Django 2.1.7 on 2019-03-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190317_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nome',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
