# Generated by Django 2.1.7 on 2019-03-16 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190314_2135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aluno',
            new_name='Estudante',
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name_plural': 'Mentores'},
        ),
        migrations.RenameField(
            model_name='contato',
            old_name='aluno',
            new_name='estudante',
        ),
        migrations.RenameField(
            model_name='contato',
            old_name='professor',
            new_name='mentor',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='alunos',
            new_name='estudantes',
        ),
    ]
