# Generated by Django 2.1.7 on 2019-03-16 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190316_1259'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Professor',
            new_name='Mentor',
        ),
    ]
